const dates = [
  {title:"template", social:"social1", energy:"energy2"},
  {title:"beachWalk", text:"go for a walk along the beach", social:"social1", energy:"energy1"},
  {title: "bar", text: "go to the pub (or bar or whatevs)", social:"social3", energy:"energy3"},
  {title:"paintAndSip", text:"do a Paint and Sip! Or some such thing.", social:"social3", energy:"energy2", tags:['art']},
  {title:"restaurant", text:"go to a restaurant! New or liked.", social:"social2", energy:"energy1", tags:[]},
  {title:"bushWalk", text:"go for a nature walk/bush walk", social:"social1", energy:"energy2", tags:['healthy']},
  {title:"hike", text:"go for a hike! :S", social:"social1", energy:"energy3", tags:['healthy']},
  {title:"boardGames", text:"have a board game night? Maybe competitive scrabble", social:"social1", energy:"energy1", tags:[]},
  {title:"gallery", text:"find an art gallery to visit", social:"social1", energy:"energy2", tags:['art']},
  {title:"movies", text:"go to the movies! If there's something good, see that. Otherwise why not roll those dice!", social:"social1", energy:"energy1", tags:[]},
  {title:"cookingClass", text:"find a cooking class to do", social:"social3", energy:"energy3", tags:[]},
  {title:"liveBand", text:"if there are no bands you know, your dad is probably playing somewhere this weekend lmao", social:"social3", energy:"energy2", tags:[]},
  {title:"dragShow", text:"find a drag show! (might have to look out of town)", social:"social2", energy:"energy2", tags:[]},
  {title:"picnic", text:"just have a picnic :)", social:"social1", energy:"energy1", tags:[]},
  {title:"beach", text:"go to the beach to swim(if summer) or just look(if winter)", social:"social1", energy:"energy1", tags:[]},
  {title:"dayTrip", text:"take a day trip to a different town", social:"social1", energy:"energy3", tags:[]},
  {title:"antiquing", text:"visit some antique shops", social:"social1", energy:"energy1", tags:[]},
  {title:"thrift", text:"visit some op shops, find that heat", social:"social1", energy:"energy1", tags:[]},
  {title:"aquarium", text:"go to an aquarium (if those are still a thing)", social:"social1", energy:"energy2", tags:[]},
  {title:"pub", text:"just go out! Bernie's is prolly open", social:"social3", energy:"energy3", tags:[]},
  {title:"coffee", text:"find a nice (iced) coffee place", social:"social1", energy:"energy1", tags:['day']},
  {title:"horseTime", text:"go ride a horse lmaooooo", social:"social2", energy:"energy3", tags:['booked']},
  {title:"escapeRoom", text:"go do an escape room :)", social:"social2", energy:"energy2", tags:['booked']},
  {title:"openHouse", text:"go to an open house just to judge it", social:"social2", energy:"energy2", tags:[]},
  {title:"miniGolf", text:"go play mini golf (or regular golf if you're like that :/ )", social:"social2", energy:"energy1", tags:['booked']},
  {title:"shoppingClothes", text:"go clothes shopping, even just window shopping", social:"social1", energy:"energy2", tags:[]},
  {title:"zoo", text:"go to a zoo or a less problematic version", social:"social1", energy:"energy2", tags:[]},
  {title:"museum", text:"go to a museum like we're brittish", social:"social1", energy:"energy2", tags:[]},
  {title:"camping", text:"go camping if ur one of those people :)", social:"social1", energy:"energy3", tags:[]},
  {title:"cookOff", text:"have a cook off! Pick a meal and see who can make it better", social:"social1", energy:"energy1", tags:['healthy']},
  {title:"workOut", text:"have a work out date, go gym or run or climb etc", social:"social1", energy:"energy2", tags:['healthy']},
  {title:"videoGame", text:"just play some video games together, if ur into it", social:"social1", energy:"energy1", tags:[]},
  {title:"albumParty", text:"have an album listen party where you both bring an album to critique", social:"social1", energy:"energy1", tags:[]},
]

//export default dates;